name: Development Pipeline

on:
  push:
    branches: ["feature/**", "fix/**", "chore/**", "refactor/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
